#set( $symbol_dollar = '$' )
AWSTemplateFormatVersion: 2010-09-09

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ParamLambda:
    Description: Example Lambda Param
    Default: Test123
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunction

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../target/lambda.jar
      Handler: ${package}.MainHandler
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          EXAMPLE_PARAM: !Ref ParamLambda
      Events:
        ProxyEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ':'
          - !Ref AWS::AccountId
          - ':'
          - !Ref Api
          - '/*'

Outputs:
  ApiGatewayUri:
    Value: !Join
      - ''
      - - 'https://'
        - !Ref Api
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/prod/'


